# Generated by Django 3.2.16 on 2024-06-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('fromU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='jitter.user')),
                ('toU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='jitter.user')),
            ],
        ),
    ]
