# Generated by Django 3.2.16 on 2024-06-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitter', '0002_user_bunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bunks',
            field=models.ManyToManyField(related_name='bunked_users', to='jitter.Bunk'),
        ),
    ]
